extension SpriteArt {
    static let raptorPalette: Palette = [
        "G": Colors.leaf, "N": Colors.darkLeaf, "L": Colors.paleLeaf,
        "E": Colors.eyeWhite, "P": Colors.pupil, "W": PixelColor(0xFFFFFF), "C": Colors.sand, "R": Colors.red,
    ]

    static let raptor: [String: [String]] = [
        "walk1": [
            "................",
            "........NGGGGN..",
            ".......NGGEPGGN.",
            ".......NGGGGGGGN",
            "N......NGGGGWWGN",
            "NN....NGGGGGGGG.",
            ".NG..NGGGGGGGN..",
            ".NGGNGGGGGGGN...",
            "..NGGGGGGGGG....",
            "...NGGLLLGGGGN..",
            "....NGLLLLGGN...",
            ".....NGGGGGN....",
            ".....NGG.NGG....",
            ".....NG...NG....",
            "....NGG....NG...",
            "....CCC....CCC..",
        ],
        "walk2": [
            "................",
            "........NGGGGN..",
            ".......NGGEPGGN.",
            ".......NGGGGGGGN",
            "N......NGGGGWWGN",
            "NN....NGGGGGGGG.",
            ".NG..NGGGGGGGN..",
            ".NGGNGGGGGGGN...",
            "..NGGGGGGGGG....",
            "...NGGLLLGGGGN..",
            "....NGLLLLGGN...",
            ".....NGGGGGN....",
            "......NGGGN.....",
            ".......NGG......",
            "......NGGGN.....",
            "......CCCCC.....",
        ],
        "squished": [
            "................",
            "................",
            "................",
            "................",
            "................",
            "................",
            "................",
            "................",
            "................",
            "................",
            ".......NGGGGGN..",
            "N.....NGGEPGGGN.",
            "NN...NGGGGGWWGN.",
            ".NGGNGGGLLLGGGGN",
            "..NGGGGGLLLLGGN.",
            "...CCCCNNNNCCCC.",
        ],
    ]

    static let ankyPalette: Palette = [
        "B": Colors.brown, "N": Colors.darkBrown, "T": Colors.tan, "S": Colors.sand,
        "E": Colors.eyeWhite, "P": Colors.pupil, "C": Colors.sand,
    ]

    static let anky: [String: [String]] = [
        "walk1": [
            "................",
            "................",
            "......S...S.....",
            "....S.TTTTT.S...",
            "...NTTTTTTTTTN..",
            "..NTTTSTTTSTTTN.",
            ".NTTTTTTTTTTTTTN",
            ".NTTTTTTTTTTTTBN",
            "N.NBBBBBBBBBBBBB",
            "N..NBBBBBBBBBBEB",
            ".N..NBBBBBBBBBBP",
            "..N..NBBBBBBBBBN",
            "...N.NBBBNBBBBN.",
            "....NBB...NBB...",
            "....NBN...NBN...",
            "....CCC...CCC...",
        ],
        "walk2": [
            "................",
            "................",
            "......S...S.....",
            "....S.TTTTT.S...",
            "...NTTTTTTTTTN..",
            "..NTTTSTTTSTTTN.",
            ".NTTTTTTTTTTTTTN",
            ".NTTTTTTTTTTTTBN",
            "N.NBBBBBBBBBBBBB",
            "N..NBBBBBBBBBBEB",
            ".N..NBBBBBBBBBBP",
            "..N..NBBBBBBBBBN",
            "...N.NBBBNBBBBN.",
            "......NBBBBN....",
            ".....NBB.NBB....",
            ".....CCC.CCC....",
        ],
        "ball1": [
            "................",
            "................",
            "................",
            "................",
            "......S...S.....",
            "....S.TTTTT.S...",
            "...NTTTTTTTTTN..",
            "..NTTTSTTTSTTTN.",
            ".NTTTTTTTTTTTTTN",
            ".NTTTTTTTTTTTTTN",
            ".NTTSTTTTTTSTTTN",
            ".NTTTTTTTTTTTTTN",
            "..NTTTTTTTTTTTN.",
            "...NNTTTTTTTNN..",
            ".....NNNNNNN....",
            "................",
        ],
        "ball2": [
            "................",
            "................",
            "................",
            "................",
            ".....S..S..S....",
            "....STTTTTTTS...",
            "...NTTTTTTTTTN..",
            "..NTTTTSTTTTTTN.",
            ".NTTTTTTTTTTTTTN",
            ".NTSTTTTTTTTTSTN",
            ".NTTTTTTTSTTTTTN",
            ".NTTTTTTTTTTTTTN",
            "..NTTSTTTTTTTTN.",
            "...NNTTTTTTTNN..",
            ".....NNNNNNN....",
            "................",
        ],
    ]

    static let pteroPalette: Palette = [
        "V": Colors.purple, "N": Colors.darkPurple, "L": PixelColor(0xC8A0E8),
        "E": Colors.eyeWhite, "P": Colors.pupil, "O": Colors.orange, "C": Colors.sand,
    ]

    static let ptero: [String: [String]] = [
        "fly1": [
            "N..............N",
            "NVN..........NVN",
            ".NVVN......NVVN.",
            "..NVVVN..NVVVN..",
            "...NVVVVVVVVNVN.",
            "....NVVVVVVVNVEN",
            ".....NVVVVVVVVVO",
            "......NVLLLVVNOO",
            ".......NVLLVVN..",
            "........NVVVN...",
            ".........NVN....",
            "........NC.CN...",
            "................",
            "................",
            "................",
            "................",
        ],
        "fly2": [
            "................",
            "................",
            "................",
            "...........NVN..",
            "...NVVVVVVVVNVN.",
            "..NVVVVVVVVVNVEN",
            ".NVVVVVVVVVVVVVO",
            "NVVN..NVLLLVVNOO",
            "NVN....NVLLVVN..",
            ".N......NVVVN...",
            ".........NVN....",
            "........NC.CN...",
            "................",
            "................",
            "................",
            "................",
        ],
        "walk1": [
            "................",
            "................",
            "................",
            "................",
            "...........NVN..",
            "..........NVNVN.",
            "...NVVVVVVVVNVEN",
            "..NVVVVVVVVVVVVO",
            ".NVVNVVVVVVVVNOO",
            ".NVN.NVLLLVVVN..",
            "..N...NVLLVVN...",
            ".......NVVVN....",
            "........NVN.....",
            ".......NV.VN....",
            "......NV...VN...",
            "......CC...CC...",
        ],
        "walk2": [
            "................",
            "................",
            "................",
            "................",
            "...........NVN..",
            "..........NVNVN.",
            "...NVVVVVVVVNVEN",
            "..NVVVVVVVVVVVVO",
            ".NVVNVVVVVVVVNOO",
            ".NVN.NVLLLVVVN..",
            "..N...NVLLVVN...",
            ".......NVVVN....",
            "........NVN.....",
            "........NVN.....",
            ".......NVVVN....",
            ".......CCCCC....",
        ],
    ]

    static let stegoPalette: Palette = [
        "O": Colors.orange, "N": PixelColor(0xA04810), "L": Colors.sand, "R": Colors.red, "Y": Colors.yellow,
        "E": Colors.eyeWhite, "P": Colors.pupil, "C": Colors.sand,
    ]

    static let stego: [String: [String]] = [
        "walk1": [
            "................",
            "....R....R......",
            "...RYR..RYR.....",
            "..RYYYRRYYYR....",
            "..RYYYYYYYYYR...",
            ".NOOOOOOOOOOOON.",
            "NOOOOOOOOOOOOOON",
            "NOOOOOOOOOOOONON",
            ".NOOOOOOOOOONOEN",
            "..NOOOLLLOOOOOOP",
            "...NOOLLLLOOOOON",
            "....NOOOOOOOOON.",
            ".....NOOONOOON..",
            ".....NOO..NOO...",
            "....NOO....NOO..",
            "....CCC....CCC..",
        ],
        "walk2": [
            "................",
            "....R....R......",
            "...RYR..RYR.....",
            "..RYYYRRYYYR....",
            "..RYYYYYYYYYR...",
            ".NOOOOOOOOOOOON.",
            "NOOOOOOOOOOOOOON",
            "NOOOOOOOOOOOONON",
            ".NOOOOOOOOOONOEN",
            "..NOOOLLLOOOOOOP",
            "...NOOLLLLOOOOON",
            "....NOOOOOOOOON.",
            ".....NOOONOOON..",
            "......NOOOOON...",
            ".....NOO..NOO...",
            ".....CCC..CCC...",
        ],
    ]

    static let rexPalette: Palette = [
        "R": PixelColor(0xC04030), "N": PixelColor(0x782018), "L": PixelColor(0xE8C898), "H": PixelColor(0xE06850),
        "E": Colors.yellow, "P": Colors.pupil, "W": PixelColor(0xFFFFFF), "C": Colors.sand, "F": Colors.orange, "Y": Colors.lavaBright,
        "Z": PixelColor(0x8090FF),
    ]

    private static let rexBody: [String] = [
        // rows 0..15: head
        "..................NNNNNNNNN.....",
        ".................NRRRRRRRRRN....",
        "................NRRRRRRRRRRRN...",
        "...............NRRRRRRRRRRRRRN..",
        "...............NRRREPRRRRRRRRRN.",
        "..............NRRRREPRRRRRRRRRRN",
        "..............NRRRRRRRRRRRRRRRRN",
        "..............NRRRRRRNNNNNNNNNNN",
        "..............NRRRRRRNWWWWWWWWWN",
        "..............NRRRRRRRNNNNNNNNN.",
        "..............NRRRRRRRRRRRRRRN..",
        ".............NRRRRRRRRRRRRRN....",
        "............NRRRRRRRRRRRRN......",
        "NN.........NRRRRRRRRRRRRN.......",
        "NRN.......NRRRRRRRRLLLLRRN......",
        "NRRN.....NRRRRRRRRRLLLLLLRN.....",
    ]

    static let rex: [String: [String]] = [
        "idle": rexBody + [
            ".NRRNN..NRRRRRRRRRRLLLLLLRRN....",
            "..NRRRNNRRRRRRRRRRRLLLLLLRRRN...",
            "...NRRRRRRRRRRRRRRRRLLLLRRRRN...",
            "....NRRRRRRRRRRRRRRRRLLRRRRRN...",
            ".....NNRRRRRRRRRRRRRRRRRRRRN....",
            ".......NNRRRRRRRRRRRRRRRRRN.....",
            ".........NRRRRRRRRRRRRRRRN......",
            "..........NRRRRRRRRRRRRRN.......",
            "...........NRRRRNNNRRRRN........",
            "...........NRRRN...NRRRN........",
            "...........NRRRN...NRRRN........",
            "...........NRRRN...NRRRN........",
            "...........NRRRN...NRRRN........",
            "..........NRRRRN...NRRRRN.......",
            ".........NCCCCCN...NCCCCCN......",
            ".........NNNNNNN...NNNNNNN......",
        ],
        "walk1": rexBody + [
            ".NRRNN..NRRRRRRRRRRLLLLLLRRN....",
            "..NRRRNNRRRRRRRRRRRLLLLLLRRRN...",
            "...NRRRRRRRRRRRRRRRRLLLLRRRRN...",
            "....NRRRRRRRRRRRRRRRRLLRRRRRN...",
            ".....NNRRRRRRRRRRRRRRRRRRRRN....",
            ".......NNRRRRRRRRRRRRRRRRRN.....",
            ".........NRRRRRRRRRRRRRRRN......",
            "..........NRRRRRRRRRRRRRN.......",
            "..........NRRRRNNNNRRRRRN.......",
            ".........NRRRN.....NRRRRN.......",
            "........NRRRN.......NRRRRN......",
            ".......NRRRN.........NRRRRN.....",
            "......NRRRN...........NRRRN.....",
            ".....NRRRRN...........NRRRRN....",
            "....NCCCCCN...........NCCCCCN...",
            "....NNNNNNN...........NNNNNNN...",
        ],
        "walk2": rexBody + [
            ".NRRNN..NRRRRRRRRRRLLLLLLRRN....",
            "..NRRRNNRRRRRRRRRRRLLLLLLRRRN...",
            "...NRRRRRRRRRRRRRRRRLLLLRRRRN...",
            "....NRRRRRRRRRRRRRRRRLLRRRRRN...",
            ".....NNRRRRRRRRRRRRRRRRRRRRN....",
            ".......NNRRRRRRRRRRRRRRRRRN.....",
            ".........NRRRRRRRRRRRRRRRN......",
            "..........NRRRRRRRRRRRRRN.......",
            "...........NRRRRRRRRRRRN........",
            "............NRRRRRRRRRN.........",
            "............NRRRRNRRRRN.........",
            "............NRRRN.NRRRN.........",
            "............NRRRN.NRRRN.........",
            "...........NRRRRN.NRRRRN........",
            "..........NCCCCCN.NCCCCCN.......",
            "..........NNNNNNN.NNNNNNN.......",
        ],
        "leap": rexBody + [
            ".NRRNN..NRRRRRRRRRRLLLLLLRRN....",
            "..NRRRNNRRRRRRRRRRRLLLLLLRRRN...",
            "...NRRRRRRRRRRRRRRRRLLLLRRRRN...",
            "....NRRRRRRRRRRRRRRRRLLRRRRRN...",
            ".....NNRRRRRRRRRRRRRRRRRRRRN....",
            ".......NNRRRRRRRRRRRRRRRRRN.....",
            ".........NRRRRRRRRRRRRRRRN......",
            "..........NRRRRRRRRRRRRRN.......",
            "..........NRRRRRRNNRRRRRRN......",
            ".........NRRRRRRN..NRRRRRRN.....",
            "........NRRRRRRN....NRRRRRRN....",
            "........NCCCCCN......NCCCCCN....",
            "........NNNNNN........NNNNNN....",
            "................................",
            "................................",
            "................................",
        ],
        "stun": [
            "........Z......Z.....Z..........",
            "..................NNNNNNNNN.....",
            ".................NRRRRRRRRRN....",
            "................NRRRRRRRRRRRN...",
            "...............NRRRRRRRRRRRRRN..",
            "...............NRRRPEPRRRRRRRRN.",
            "..............NRRRRPEPRRRRRRRRRN",
            "..............NRRRRRRRRRRRRRRRRN",
            "..............NRRRRRRNNNNNNNNNNN",
            "..............NRRRRRRNWWWWWWWWWN",
            "..............NRRRRRRRNNNNNNNNN.",
            "..............NRRRRRRRRRRRRRRN..",
            ".............NRRRRRRRRRRRRRN....",
            "............NRRRRRRRRRRRRN......",
            "NN.........NRRRRRRRRRRRRN.......",
            "NRN.......NRRRRRRRRLLLLRRN......",
            "NRRN.....NRRRRRRRRRLLLLLLRN.....",
            ".NRRNN..NRRRRRRRRRRLLLLLLRRN....",
            "..NRRRNNRRRRRRRRRRRLLLLLLRRRN...",
            "...NRRRRRRRRRRRRRRRRLLLLRRRRN...",
            "....NRRRRRRRRRRRRRRRRLLRRRRRN...",
            ".....NNRRRRRRRRRRRRRRRRRRRRN....",
            ".......NNRRRRRRRRRRRRRRRRRN.....",
            ".........NRRRRRRRRRRRRRRRN......",
            "..........NRRRRRRRRRRRRRN.......",
            "..........NRRRRRRNNRRRRRRN......",
            ".........NRRRRRRN..NRRRRRRN.....",
            "........NRRRRRRN....NRRRRRRN....",
            ".......NRRRRRRN......NRRRRRRN...",
            "......NRRRRRRN........NRRRRRRN..",
            ".....NCCCCCCN..........NCCCCCCN.",
            ".....NNNNNNNN..........NNNNNNNN.",
        ],
        "roar": [
            "..................NNNNNNNNN.....",
            ".................NRRRRRRRRRN....",
            "................NRRRRRRRRRRRN...",
            "...............NRRRRRRRRRRRRRN..",
            "...............NRRREPRRRRRRRRRN.",
            "..............NRRRREPRRRRRRRRRRN",
            "..............NRRRRRRRRRRRRRRRRN",
            "..............NRRRRRRNNNNNNNNNNN",
            "..............NRRRRRRNWWWWWWWWWN",
            "..............NRRRRRRNFFFFFFFFYY",
            "..............NRRRRRRNFFFFFFYYY.",
            "..............NRRRRRRNWWWWWWWWN.",
            "..............NRRRRRRRNNNNNNNN..",
            "NN............NRRRRRRRRRRRRN....",
            "NRN..........NRRRRRRRRRRRN......",
            "NRRN........NRRRRRRRLLLLRN......",
            ".NRRNN.....NRRRRRRRRLLLLLLN.....",
            "..NRRRNN..NRRRRRRRRRLLLLLLRN....",
            "...NRRRRNNRRRRRRRRRRRLLLLRRN....",
            "....NRRRRRRRRRRRRRRRRRLLRRRRN...",
            ".....NNRRRRRRRRRRRRRRRRRRRRN....",
            ".......NNRRRRRRRRRRRRRRRRRN.....",
            ".........NRRRRRRRRRRRRRRRN......",
            "..........NRRRRRRRRRRRRRN.......",
            "...........NRRRRNNNRRRRN........",
            "...........NRRRN...NRRRN........",
            "...........NRRRN...NRRRN........",
            "...........NRRRN...NRRRN........",
            "...........NRRRN...NRRRN........",
            "..........NRRRRN...NRRRRN.......",
            ".........NCCCCCN...NCCCCCN......",
            ".........NNNNNNN...NNNNNNN......",
        ],
    ]

    static let fireballPalette: Palette = ["F": Colors.orange, "Y": Colors.lavaBright, "W": PixelColor(0xFFF8D0), "R": Colors.red]

    static let fireball: [String: [String]] = [
        "1": [
            "....RFFFYY......",
            "..RFFFYYYWWY....",
            ".RFFYYYWWWWWYY..",
            "RFFYYYWWWWWWYYY.",
            "RFFYYYWWWWWWYYY.",
            ".RFFYYYWWWWWYY..",
            "..RFFFYYYWWY....",
            "....RFFFYY......",
        ],
        "2": [
            "......RFFYY.....",
            "...RRFFFYYWY....",
            ".RRFFFYYYWWWYY..",
            "RRFFYYYWWWWWWYY.",
            "RRFFYYYWWWWWWYY.",
            ".RRFFFYYYWWWYY..",
            "...RRFFFYYWY....",
            "......RFFYY.....",
        ],
    ]

    static let dinos: [String: PixelSprite] = {
        var out: [String: PixelSprite] = [:]
        func add(_ prefix: String, _ palette: Palette, _ poses: [String: [String]], flash: Bool = false) {
            for (pose, rows) in poses {
                let sprite = PixelSprite(palette: palette, rows: rows)
                out["\(prefix).\(pose)"] = sprite
                if flash { out["\(prefix).\(pose)@flash"] = sprite.flashedWhite() }
            }
        }
        add("raptor", raptorPalette, raptor)
        add("anky", ankyPalette, anky)
        add("ptero", pteroPalette, ptero)
        add("stego", stegoPalette, stego)
        add("rex", rexPalette, rex, flash: true)
        add("fireball", fireballPalette, fireball)
        return out
    }()
}
