extension SpriteArt {
    static let ninjaPalette: Palette = [
        "K": PixelColor(0x202838),   // gi
        "D": PixelColor(0x101820),   // gi shadow
        "H": PixelColor(0x3C4868),   // gi highlight
        "R": PixelColor(0x2868E8),   // bandana
        "S": Colors.skin,
        "E": Colors.eyeWhite,
        "P": Colors.pupil,
        "Y": Colors.gold,            // belt
        "W": PixelColor(0xE8E8F0),   // shuriken glint
        "G": PixelColor(0x707880),   // shuriken steel
    ]

    static let shurikenFormPalette: Palette = ninjaPalette.merging([
        "K": PixelColor(0xE8E8F0), "D": PixelColor(0xA8B0C0), "H": PixelColor(0xFFFFFF), "R": PixelColor(0x2868E8), "Y": PixelColor(0x202838),
    ]) { _, new in new }

    static let goldPalettes: [Palette] = [
        ninjaPalette.merging(["K": Colors.gold, "D": Colors.darkGold, "H": Colors.paleGold, "R": PixelColor(0xFFFFFF)]) { _, new in new },
        ninjaPalette.merging(["K": Colors.orange, "D": Colors.darkGold, "H": Colors.yellow, "R": PixelColor(0xFFFFFF)]) { _, new in new },
        ninjaPalette.merging(["K": PixelColor(0xFFFFFF), "D": Colors.paleGold, "H": PixelColor(0xFFFFFF), "R": Colors.gold]) { _, new in new },
    ]

    static let ninjaSmall: [String: [String]] = [
        "idle": [
            "......KKKK......",
            ".....KKKKKK.....",
            "....KKKKKKKK....",
            "..RRRRRRRRRRR...",
            ".R..KSSSSSSK....",
            "....KSEPSEPK....",
            "....KKSSSSKK....",
            ".....KKKKKK.....",
            "....KKKHHKKK....",
            "...KKKKHHKKKK...",
            "...SKKYYYYKKS...",
            "....KKKKKKKK....",
            ".....KKKKKK.....",
            ".....KK..KK.....",
            ".....KK..KK.....",
            "....DDD..DDD....",
        ],
        "walk1": [
            "......KKKK......",
            ".....KKKKKK.....",
            "....KKKKKKKK....",
            "..RRRRRRRRRRR...",
            ".R..KSSSSSSK....",
            "....KSEPSEPK....",
            "....KKSSSSKK....",
            ".....KKKKKK.....",
            "....KKKHHKKKS...",
            "...SKKKHHKKK....",
            "....KKYYYYKK....",
            "....KKKKKKKK....",
            ".....KKKKKK.....",
            "....KK....KK....",
            "...KK......KK...",
            "..DDD......DDD..",
        ],
        "walk2": [
            "......KKKK......",
            ".....KKKKKK.....",
            "....KKKKKKKK....",
            "..RRRRRRRRRRR...",
            ".R..KSSSSSSK....",
            "....KSEPSEPK....",
            "....KKSSSSKK....",
            ".....KKKKKK.....",
            "....KKKHHKKK....",
            "...SKKKHHKKKS...",
            "....KKYYYYKK....",
            "....KKKKKKKK....",
            ".....KKKKKK.....",
            "......KKKK......",
            "......KKKK......",
            ".....DDDDDD.....",
        ],
        "jump": [
            "......KKKK......",
            ".....KKKKKK.....",
            "....KKKKKKKK....",
            "..RRRRRRRRRRR...",
            ".R..KSSSSSSK....",
            "....KSEPSEPK....",
            "....KKSSSSKK....",
            "..S..KKKKKK..S..",
            "..K.KKKHHKKK.K..",
            "...KKKKHHKKKK...",
            "....KKYYYYKK....",
            "....KKKKKKKK....",
            "...KKKK..KKKK...",
            "...DDD....DDD...",
            "................",
            "................",
        ],
        "dead": [
            "................",
            "......KKKK......",
            ".....KKKKKK.....",
            "....KKKKKKKK....",
            "..RRRRRRRRRRR...",
            ".R..KSSSSSSK....",
            "....KSPSPSPK....",
            "....KKSSSSKK....",
            ".....KKKKKK.....",
            "..S.KKKHHKKK.S..",
            "..KKKKKHHKKKKK..",
            "....KKYYYYKK....",
            "....KKKKKKKK....",
            "...KKKK..KKKK...",
            "...DDD....DDD...",
            "................",
        ],
        "sword1": [
            "............W...",
            "............W...",
            "......KKKK..W...",
            ".....KKKKKK.G...",
            "....KKKKKKKKG...",
            "..RRRRRRRRRRR...",
            ".R..KSSSSSSK.Y..",
            "....KSEPSEPK.S..",
            "....KKSSSSKKKK..",
            ".....KKKKKK.....",
            "....KKKHHKKK....",
            "...SKKKHHKKK....",
            "....KKYYYYKK....",
            "....KKKKKKKK....",
            ".....KK..KK.....",
            "....DDD..DDD....",
        ],
        "sword2": [
            "................",
            "................",
            "....KKKK........",
            "...KKKKKK.......",
            "..KKKKKKKK......",
            "RRRRRRRRRRR.....",
            "..KSSSSSSK......",
            "..KSEPSEPK......",
            "..KKSSSSKK......",
            "...KKKKKK.......",
            "..KKKHHKKKSYGGWW",
            ".SKKKHHKKK......",
            "..KKYYYYKK......",
            "..KKKKKKKK......",
            "...KK..KK.......",
            "..DDD..DDD......",
        ],
        "sword3": [
            "................",
            "................",
            "....KKKK........",
            "...KKKKKK.......",
            "..KKKKKKKK......",
            "RRRRRRRRRRR.....",
            "..KSSSSSSK......",
            "..KSEPSEPK......",
            "..KKSSSSKK......",
            "...KKKKKK.......",
            "..KKKHHKKK......",
            ".SKKKHHKKKS.....",
            "..KKYYYYKKKY....",
            "..KKKKKKKK..G...",
            "...KK..KK....GW.",
            "..DDD..DDD.....W",
        ],
        "sword4": [
            "................",
            "................",
            "......KKKK......",
            ".....KKKKKK.....",
            "....KKKKKKKK....",
            "..RRRRRRRRRRR...",
            ".R..KSSSSSSK....",
            "....KSEPSEPK....",
            "....KKSSSSKK....",
            ".....KKKKKK.....",
            "....KKKHHKKKS...",
            "...SKKKHHKKKY...",
            "....KKYYYYKKG...",
            "....KKKKKKKKG...",
            ".....KK..KK.W...",
            "....DDD..DDD....",
        ],
    ]

    static let ninjaBig: [String: [String]] = [
        "idle": [
            "......KKKK......",
            ".....KKKKKK.....",
            "....KKKKKKKK....",
            "....KKKKKKKK....",
            "..RRRRRRRRRRR...",
            ".R..KSSSSSSK....",
            "R...KSEPSEPK....",
            "....KSSSSSSK....",
            "....KKSSSSKK....",
            ".....KKKKKK.....",
            "....KKKKKKKK....",
            "...KKKKKKKKKK...",
            "..KKKKKHHKKKKK..",
            "..KKKKKHHKKKKK..",
            "..SKKKKHHKKKKS..",
            "..S.KKKKKKKK.S..",
            "....KKYYYYKK....",
            "....KKYYYYKK....",
            "....KKKKKKKK....",
            "....KKKKKKKK....",
            "....KKKKKKKK....",
            "....KKK..KKK....",
            "....KKK..KKK....",
            "....KKK..KKK....",
            "....KKK..KKK....",
            "....KKK..KKK....",
            "....KKK..KKK....",
            "....KKK..KKK....",
            "....KKK..KKK....",
            "....KKK..KKK....",
            "...DDDD..DDDD...",
            "...DDDD..DDDD...",
        ],
        "walk1": [
            "......KKKK......",
            ".....KKKKKK.....",
            "....KKKKKKKK....",
            "....KKKKKKKK....",
            "..RRRRRRRRRRR...",
            ".R..KSSSSSSK....",
            "R...KSEPSEPK....",
            "....KSSSSSSK....",
            "....KKSSSSKK....",
            ".....KKKKKK.....",
            "....KKKKKKKK....",
            "...KKKKKKKKKKS..",
            "..KKKKKHHKKKKS..",
            "..KKKKKHHKKKK...",
            "..SKKKKHHKKKK...",
            "..S.KKKKKKKK....",
            "....KKYYYYKK....",
            "....KKYYYYKK....",
            "....KKKKKKKK....",
            "....KKKKKKKK....",
            "....KKKKKKKK....",
            "...KKKK..KKKK...",
            "...KKK....KKK...",
            "..KKK......KKK..",
            "..KKK......KKK..",
            ".KKK........KKK.",
            ".KKK........KKK.",
            ".KKK........KKK.",
            ".KKK........KKK.",
            ".KKK........KKK.",
            "DDDD........DDDD",
            "DDDD........DDDD",
        ],
        "walk2": [
            "......KKKK......",
            ".....KKKKKK.....",
            "....KKKKKKKK....",
            "....KKKKKKKK....",
            "..RRRRRRRRRRR...",
            ".R..KSSSSSSK....",
            "R...KSEPSEPK....",
            "....KSSSSSSK....",
            "....KKSSSSKK....",
            ".....KKKKKK.....",
            "....KKKKKKKK....",
            "...KKKKKKKKKK...",
            "..KKKKKHHKKKKK..",
            "..SKKKKHHKKKKS..",
            "..S.KKKHHKKK.S..",
            "....KKKKKKKK....",
            "....KKYYYYKK....",
            "....KKYYYYKK....",
            "....KKKKKKKK....",
            "....KKKKKKKK....",
            "....KKKKKKKK....",
            ".....KKKKKK.....",
            ".....KKKKKK.....",
            ".....KKKKKK.....",
            ".....KKKKKK.....",
            ".....KKKKKK.....",
            ".....KKKKKK.....",
            ".....KKKKKK.....",
            ".....KKKKKK.....",
            ".....KKKKKK.....",
            "....DDDDDDDD....",
            "....DDDDDDDD....",
        ],
        "jump": [
            "......KKKK......",
            ".....KKKKKK.....",
            "....KKKKKKKK....",
            "....KKKKKKKK....",
            "..RRRRRRRRRRR...",
            ".R..KSSSSSSK....",
            "R...KSEPSEPK....",
            "....KSSSSSSK....",
            "..S.KKSSSSKK.S..",
            "..K..KKKKKK..K..",
            "..K.KKKKKKKK.K..",
            "..KKKKKKKKKKKK..",
            "...KKKKHHKKKK...",
            "....KKKHHKKK....",
            "....KKKHHKKK....",
            "....KKKKKKKK....",
            "....KKYYYYKK....",
            "....KKYYYYKK....",
            "....KKKKKKKK....",
            "....KKKKKKKK....",
            "...KKKKKKKKKK...",
            "...KKKK..KKKK...",
            "..KKKK....KKKK..",
            "..KKK......KKK..",
            "..KKK......KKK..",
            "..DDD......DDD..",
            "..DDD......DDD..",
            "................",
            "................",
            "................",
            "................",
            "................",
        ],
        "throw": [
            "......KKKK......",
            ".....KKKKKK.....",
            "....KKKKKKKK....",
            "....KKKKKKKK....",
            "..RRRRRRRRRRR...",
            ".R..KSSSSSSK....",
            "R...KSEPSEPK....",
            "....KSSSSSSK....",
            "....KKSSSSKK....",
            ".....KKKKKK.....",
            "....KKKKKKKK....",
            "...KKKKKKKKKKKKS",
            "..KKKKKHHKKKKKK.",
            "..KKKKKHHKKKK...",
            "..SKKKKHHKKKK...",
            "..S.KKKKKKKK....",
            "....KKYYYYKK....",
            "....KKYYYYKK....",
            "....KKKKKKKK....",
            "....KKKKKKKK....",
            "....KKKKKKKK....",
            "....KKK..KKK....",
            "....KKK..KKK....",
            "....KKK..KKK....",
            "....KKK..KKK....",
            "....KKK..KKK....",
            "....KKK..KKK....",
            "....KKK..KKK....",
            "....KKK..KKK....",
            "....KKK..KKK....",
            "...DDDD..DDDD...",
            "...DDDD..DDDD...",
        ],
        "sword1": [
            "......KKKK......",
            ".....KKKKKK.....",
            "....KKKKKKKK....",
            "....KKKKKKKK....",
            "..RRRRRRRRRRR...",
            ".R..KSSSSSSK....",
            "R...KSEPSEPK....",
            "....KSSSSSSK....",
            "....KKSSSSKK....",
            ".....KKKKKK.....",
            "....KKKKKKKK.W..",
            "...KKKKKKKKK.W..",
            "..KKKKKHHKKKKW..",
            "..KKKKKHHKKKKG..",
            "..SKKKKHHKKKKG..",
            "..S.KKKKKKKKSY..",
            "....KKYYYYKK....",
            "....KKYYYYKK....",
            "....KKKKKKKK....",
            "....KKKKKKKK....",
            "....KKKKKKKK....",
            "....KKK..KKK....",
            "....KKK..KKK....",
            "....KKK..KKK....",
            "....KKK..KKK....",
            "....KKK..KKK....",
            "....KKK..KKK....",
            "....KKK..KKK....",
            "....KKK..KKK....",
            "....KKK..KKK....",
            "...DDDD..DDDD...",
            "...DDDD..DDDD...",
        ],
        "sword2": [
            "......KKKK......",
            ".....KKKKKK.....",
            "....KKKKKKKK....",
            "....KKKKKKKK....",
            "..RRRRRRRRRRR...",
            ".R..KSSSSSSK....",
            "R...KSEPSEPK....",
            "....KSSSSSSK....",
            "....KKSSSSKK....",
            ".....KKKKKK.....",
            "....KKKKKKKK....",
            "...KKKKKKKKKK...",
            "..KKKKKHHKKKKKSY",
            "..KKKKKHHKKKKKGW",
            "..SKKKKHHKKKK...",
            "..S.KKKKKKKK....",
            "....KKYYYYKK....",
            "....KKYYYYKK....",
            "....KKKKKKKK....",
            "....KKKKKKKK....",
            "....KKKKKKKK....",
            "....KKK..KKK....",
            "....KKK..KKK....",
            "....KKK..KKK....",
            "....KKK..KKK....",
            "....KKK..KKK....",
            "....KKK..KKK....",
            "....KKK..KKK....",
            "....KKK..KKK....",
            "....KKK..KKK....",
            "...DDDD..DDDD...",
            "...DDDD..DDDD...",
        ],
        "sword3": [
            "......KKKK......",
            ".....KKKKKK.....",
            "....KKKKKKKK....",
            "....KKKKKKKK....",
            "..RRRRRRRRRRR...",
            ".R..KSSSSSSK....",
            "R...KSEPSEPK....",
            "....KSSSSSSK....",
            "....KKSSSSKK....",
            ".....KKKKKK.....",
            "....KKKKKKKK....",
            "...KKKKKKKKKK...",
            "..KKKKKHHKKKKK..",
            "..KKKKKHHKKKKK..",
            "..SKKKKHHKKKKS..",
            "..S.KKKKKKKK.Y..",
            "....KKYYYYKK.G..",
            "....KKYYYYKK.W..",
            "....KKKKKKKK....",
            "....KKKKKKKK....",
            "....KKKKKKKK....",
            "....KKK..KKK....",
            "....KKK..KKK....",
            "....KKK..KKK....",
            "....KKK..KKK....",
            "....KKK..KKK....",
            "....KKK..KKK....",
            "....KKK..KKK....",
            "....KKK..KKK....",
            "....KKK..KKK....",
            "...DDDD..DDDD...",
            "...DDDD..DDDD...",
        ],
        "sword4": [
            "......KKKK......",
            ".....KKKKKK.....",
            "....KKKKKKKK....",
            "....KKKKKKKK....",
            "..RRRRRRRRRRR...",
            ".R..KSSSSSSK....",
            "R...KSEPSEPK....",
            "....KSSSSSSK....",
            "....KKSSSSKK....",
            ".....KKKKKK.....",
            "....KKKKKKKK....",
            "...KKKKKKKKKK...",
            "..KKKKKHHKKKKK..",
            "..KKKKKHHKKKKK..",
            "..SKKKKHHKKKKK..",
            "..S.KKKKKKKKS...",
            "....KKYYYYKKY...",
            "....KKYYYYKKG...",
            "....KKKKKKKKG...",
            "....KKKKKKKKW...",
            "....KKKKKKKKW...",
            "....KKK..KKK....",
            "....KKK..KKK....",
            "....KKK..KKK....",
            "....KKK..KKK....",
            "....KKK..KKK....",
            "....KKK..KKK....",
            "....KKK..KKK....",
            "....KKK..KKK....",
            "....KKK..KKK....",
            "...DDDD..DDDD...",
            "...DDDD..DDDD...",
        ],
    ]

    static let ninja: [String: PixelSprite] = {
        var out: [String: PixelSprite] = [:]
        func add(_ prefix: String, _ poses: [String: [String]]) {
            for (pose, rows) in poses {
                out["\(prefix).\(pose)"] = PixelSprite(palette: ninjaPalette, rows: rows)
                out["\(prefix).\(pose)@shuriken"] = PixelSprite(palette: shurikenFormPalette, rows: rows)
                for (index, palette) in goldPalettes.enumerated() {
                    out["\(prefix).\(pose)@gold\(index + 1)"] = PixelSprite(palette: palette, rows: rows)
                }
            }
        }
        add("ninja.small", ninjaSmall)
        add("ninja.big", ninjaBig)
        return out
    }()
}
