#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=6
BUNDLE_ID="dev.rbstp.ninjasaurus"
PROFILE_NAME="Ninjasaurus App Store"
TEAM_ID="RM3UT3MMSR"

expand() { printf '%s' "${1/#\~/$HOME}"; }

banner "Ninjasaurus: Apple signing and TestFlight setup"

stage "Apple Distribution certificate"
say "Only Apple Distribution certificates can sign iOS builds; the Developer ID one is macOS only."
step "Xcode > Settings > Apple Accounts > your team > Manage Certificates."
step "Click + and pick 'Apple Distribution'. Add 'Apple Development' too for cable installs."
step "Keychain Access > My Certificates > right-click 'Apple Distribution: ...' > Export, format .p12, choose a password."
ask P12_PATH "Path to the exported .p12:"
P12_PATH=$(expand "$P12_PATH")
[[ -f "$P12_PATH" ]] || { warn "no file at $P12_PATH"; exit 1; }
ask_secret P12_PASSWORD "Export password:"
if openssl pkcs12 -in "$P12_PATH" -nokeys -passin "pass:$P12_PASSWORD" -legacy 2>/dev/null | openssl x509 -noout -subject | grep -q "Apple Distribution"; then
  say "certificate checks out: Apple Distribution"
elif openssl pkcs12 -in "$P12_PATH" -nokeys -passin "pass:$P12_PASSWORD" 2>/dev/null | openssl x509 -noout -subject | grep -q "Apple Distribution"; then
  say "certificate checks out: Apple Distribution"
else
  warn "could not verify the .p12 (wrong password, or not an Apple Distribution certificate)"
  confirm "Continue anyway?" || exit 1
fi
set_secret APPLE_DIST_CERT_P12 "$(base64 -i "$P12_PATH")"
set_secret APPLE_DIST_CERT_PASSWORD "$P12_PASSWORD"

stage "App ID"
say "The bundle identifier must be registered once."
open_url "https://developer.apple.com/account/resources/identifiers/list"
step "Check that an App ID with identifier $BUNDLE_ID exists. If not: + > App IDs > App > explicit $BUNDLE_ID, no capabilities."
pause "Press Enter when it exists."

stage "App Store provisioning profile"
open_url "https://developer.apple.com/account/resources/profiles/list"
step "+ > Distribution: App Store Connect > App ID $BUNDLE_ID > the Apple Distribution certificate."
step "Name it exactly: $PROFILE_NAME. Download the .mobileprovision."
ask PROFILE_PATH "Path to the .mobileprovision:"
PROFILE_PATH=$(expand "$PROFILE_PATH")
[[ -f "$PROFILE_PATH" ]] || { warn "no file at $PROFILE_PATH"; exit 1; }
plist=$(security cms -D -i "$PROFILE_PATH")
name=$(printf '%s' "$plist" | /usr/libexec/PlistBuddy -c 'Print Name' /dev/stdin 2>/dev/null || true)
appid=$(printf '%s' "$plist" | /usr/libexec/PlistBuddy -c 'Print Entitlements:application-identifier' /dev/stdin 2>/dev/null || true)
expiry=$(printf '%s' "$plist" | /usr/libexec/PlistBuddy -c 'Print ExpirationDate' /dev/stdin 2>/dev/null || true)
say "profile: ${name:-?} for ${appid:-?} (expires ${expiry:-?})"
[[ "$name" == "$PROFILE_NAME" ]] || warn "the name is not '$PROFILE_NAME'; project.yml and scripts/ExportOptions.plist expect that name"
[[ "$appid" == "$TEAM_ID.$BUNDLE_ID" ]] || warn "the profile is not for $TEAM_ID.$BUNDLE_ID"
set_secret APPLE_PROVISIONING_PROFILE "$(base64 -i "$PROFILE_PATH")"

stage "App record in App Store Connect"
open_url "https://appstoreconnect.apple.com/apps"
step "If Ninjasaurus is not listed: + > New App > iOS, name Ninjasaurus, English, bundle ID $BUNDLE_ID, SKU ninjasaurus."
pause "Press Enter when the app exists."

stage "App Store Connect API key"
say "A Team key with the Developer role (or higher) can upload builds. The notarization key from heed works if it is a Team key."
open_url "https://appstoreconnect.apple.com/access/integrations/api"
step "Team Keys tab. Reuse an existing key or Generate API Key (name Ninjasaurus CI, access Developer). Download the .p8 once."
ask KEY_PATH "Path to the AuthKey_XXXX.p8:"
KEY_PATH=$(expand "$KEY_PATH")
[[ -f "$KEY_PATH" ]] || { warn "no file at $KEY_PATH"; exit 1; }
grep -q "BEGIN PRIVATE KEY" "$KEY_PATH" || warn "that does not look like a .p8 private key"
ask KEY_ID "Key ID (10 characters, shown next to the key):"
ask ISSUER_ID "Issuer ID (UUID at the top of the Team Keys page):"
set_secret APPLE_KEY_P8 "$(base64 -i "$KEY_PATH")"
set_secret APPLE_KEY_ID "$KEY_ID"
set_secret APPLE_ISSUER_ID "$ISSUER_ID"

stage "TestFlight testers"
say "This part only works after the first build has been uploaded by the testflight workflow."
open_url "https://appstoreconnect.apple.com/apps"
step "Ninjasaurus > TestFlight > Internal Testing > + > group 'Family' > add your Apple ID."
step "Install the TestFlight app on the iPhone, accept the invitation email, install Ninjasaurus."
say "Internal testers do not go through Beta App Review, so the build is playable within minutes of processing."
pause "Press Enter to finish."

finish
